### ISSUE TITLE
[UNEXPECTED_ERROR] An unexpected error occurred. Last captured event: PACKAGE_ARTIFACTS

### ISSUE THREAD

**Issue by PeterLipcak** [stacktape/stacktape#6]
Hey guys, deploy is failing with following erorr:
[UNEXPECTED_ERROR] An unexpected error occurred. Last captured event: PACKAGE_ARTIFACTS.

Error ID: 82f82f0cc5cd40f2a58ed1becdd37926.

**Comment by simi-obs** [comment]
Hey, thanks for the report. :heart:

We have identified the issue and are currently working on a fix.

**Comment by simi-obs** [comment]
this error is fixed in the newest release. Thank you for patience. :+1:  @PeterLipcak
