### ISSUE TITLE
Stacktape CLI doesn't contain project:create command

### ISSUE THREAD

**Issue by henrymgarrett** [stacktape/stacktape#83]
In the Stacktape UI, the steps outlined to deploy a project from the CLI mention running a `project:create` command.  However, it doesn't look like the latest version of the Stacktape CLI has a command with that name.  It seems that the deploy command takes care of project creation if necessary, so the UI might just need to be updated to remove this command.

UI Screenshot:
<img width="1234" alt="Screenshot 2024-04-03 at 9 31 04 AM" src="https://github.com/stacktape/stacktape/assets/27711273/7e1322ed-8870-4661-b453-824d3d440fe7">

CLI Screenshot:
<img width="900" alt="Screenshot 2024-04-03 at 9 31 29 AM" src="https://github.com/stacktape/stacktape/assets/27711273/48ae01c2-78d9-4332-8e85-cdebe782deba">

Stacktape version: 2.5.3

**Comment by simi-obs** [comment]
This was mistake in the tutorial steps and will be corrected in the upcoming console update.

As @henrymgarrett said: Deploy command takes care of project creation if necessary.
